version: '3.8'

services:
  app:
    build:
      context: .
      target: prod
    image: compute-pi:latest
    container_name: compute-pi
    command: compute-pi
    environment:
      - PYTHONUNBUFFERED=1

  dev:
    build:
      context: .
      target: dev
    image: compute-pi:dev
    container_name: compute-pi-dev
    volumes:
      - .:/app
    command: pytest -v
    environment:
      - PYTHONUNBUFFERED=1 